name: Transform Word Document to AsciiDoc
description: Upload a Word document to have it automatically transformed into AsciiDoc format by our bot.
title: "Transformation of Word Specification"
labels: ["transformation-request", "automated-process", "triage"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        ### 📄 Transform Word to AsciiDoc
        Attach your Word document and submit. The bot will convert it to AsciiDoc and reply with a ZIP file in this thread. Ensure no sensitive/private info is in the document.

  - type: textarea
    id: word-document
    attributes:
      label: Attach Word Document
      description: Attach the `.docx` Word file for conversion.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 🔄 Processing
        After submitting the issue, the bot will start processing your document. This might take a few minutes.
        You'll receive a comment with the transformed document once the process is complete.
